/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author HP Omen
 */
public class ConverterPanel extends javax.swing.JPanel {

    public static JUnitConverterPanel[] jucps;
    public int[] converterValues;

    public ConverterPanel() {
        initComponents();
        converterValues = new int[0];
        jucps = new JUnitConverterPanel[]{
            asciiSystemPanel,
            hexSystemPanel,
            decSystemPanel1
        };
    }

    public void updateAllExcept(JUnitConverterPanel jucp, int[] newValues) {
        this.converterValues = newValues;
        if (jucp != null) {
            System.out.print("Update all except ");
            System.out.println(jucp.unitLabel.getText());
        }
        for (int i : converterValues) {
            System.out.print(i + " ");
        }
        System.out.println();
        if (converterValues.length == 0) {
            return;
        }
        if (jucp == null || asciiSystemPanel != jucp) {
            asciiSystemPanel.formatFromData();
        }
        if (jucp == null || hexSystemPanel != jucp) {
            hexSystemPanel.formatFromData();
        }
        if (jucp == null || decSystemPanel1 != jucp) {
            decSystemPanel1.formatFromData();
        }
        if (jucp == null || binSystemPanel != jucp) {
            binSystemPanel.formatFromData();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        asciiSystemPanel = new main.AsciiSystemPanel();
        hexSystemPanel = new main.HexSystemPanel();
        decSystemPanel1 = new main.DecSystemPanel();
        binSystemPanel = new main.BinSystemPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        jLabel1.setText("Delimiter:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"< >", "<;>", "<,>", "<>", "<:>", "<->"}));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(asciiSystemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                        .addComponent(decSystemPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(binSystemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hexSystemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asciiSystemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hexSystemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(binSystemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(decSystemPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        updateAllExcept(null, this.converterValues);
    }//GEN-LAST:event_jComboBox1ActionPerformed
    public String getDelimiter() {
        try {
            return ((String) this.jComboBox1.getSelectedItem()).split("<")[1].split(">")[0];
        } catch (IndexOutOfBoundsException ioobe) {
            return "";
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private main.AsciiSystemPanel asciiSystemPanel;
    private main.BinSystemPanel binSystemPanel;
    private main.DecSystemPanel decSystemPanel1;
    private main.HexSystemPanel hexSystemPanel;
    public javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
