/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

public abstract class JUnitConverterPanel extends javax.swing.JPanel {

    /**
     * Creates new form JUnitConverterPanel
     */
    public final DataSystemEncoding dataSystemEncoding;
    
    public JUnitConverterPanel(DataSystemEncoding cs, String name) {
        initComponents();
        textArea.addKeyListener(new OnlyAllowKeyAdapter(cs));
        textArea.addKeyListener(new OnKeyDownUpdate(this));
        unitLabel.setText(name.toUpperCase());
        checkBoxUePrefix.setText("");
        checkBoxUePrefix.setVisible(cs.hasPrefix);
        prefixEntry.setText(cs.prefix);
        prefixEntry.addKeyListener(new OnKeyDownReformat(this));
        dataSystemEncoding = cs;
    }

    public abstract void interpretStringTo();
    public abstract void formatFromData();
    
    private class OnKeyDownUpdate extends KeyAdapter{
        
        JUnitConverterPanel jucp;
        public OnKeyDownUpdate(JUnitConverterPanel jucp){
            this.jucp = jucp;
        }
        
        @Override
        public void keyReleased(KeyEvent e) {
            this.jucp.interpretStringTo();
            System.out.println(this.jucp.unitLabel.getText() +" update array to:");
            for(int i: Main.form.converterPanel1.converterValues){
                System.out.print(i+" ");
            }
            System.out.println();
        }
        
    }
    private class OnKeyDownReformat extends KeyAdapter{
        
        JUnitConverterPanel jucp;
        public OnKeyDownReformat(JUnitConverterPanel jucp){
            this.jucp = jucp;
        }
        
        @Override
        public void keyReleased(KeyEvent e) {
            this.jucp.formatFromData();
            System.out.println();
        }
    }
            
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        unitLabel = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        checkBoxUePrefix = new javax.swing.JCheckBox();
        prefixEntry = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setFocusable(false);
        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        setMaximumSize(new java.awt.Dimension(377, 88));
        setMinimumSize(new java.awt.Dimension(377, 88));
        setPreferredSize(new java.awt.Dimension(377, 88));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        unitLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        unitLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unitLabel.setText("unitText");

        textArea.setColumns(1);
        textArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textArea.setLineWrap(true);
        textArea.setRows(3);
        scrollPane.setViewportView(textArea);

        checkBoxUePrefix.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkBoxUePrefix.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxUePrefixItemStateChanged(evt);
            }
        });

        prefixEntry.setBackground(new java.awt.Color(240, 240, 240));
        prefixEntry.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        prefixEntry.setText("0x");
        prefixEntry.setBorder(null);
        prefixEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prefixEntryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(checkBoxUePrefix)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prefixEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prefixEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBoxUePrefix))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unitLabel))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(unitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxUePrefixItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxUePrefixItemStateChanged
        this.formatFromData();
    }//GEN-LAST:event_checkBoxUePrefixItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        StringSelection selection = new StringSelection(this.textArea.getText().replaceAll("[\n\t \r]+", " "));
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(selection, selection);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void prefixEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prefixEntryActionPerformed
        this.formatFromData();
    }//GEN-LAST:event_prefixEntryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JCheckBox checkBoxUePrefix;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JTextField prefixEntry;
    protected javax.swing.JScrollPane scrollPane;
    protected javax.swing.JTextArea textArea;
    protected javax.swing.JLabel unitLabel;
    // End of variables declaration//GEN-END:variables
}
